### ISSUE TITLE
android 7.0 mtk6373m

### ISSUE THREAD

**Issue by xulingchung2016** [jp1017/AndroidSerialPortSample#1]
android 7.0 mtk6373m 找不到串口，串口已经有root 权限了

**Comment by jp1017** [comment]
报什么错,使用串口需要root权限或系统权限

**Comment by xulingchung2016** [comment]
串口不是熟悉系统权限级别的吗？普通app 访问串口要系统签名？

**Comment by jp1017** [comment]
恩,对的,需要系统签名,其他看来root是必要的咯,哈哈

**Comment by xulingchung2016** [comment]
Preferences}: java.lang.NullPointerException: Attempt to get length of null array
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
                                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                          at android.os.Looper.loop(Looper.java:203)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6251)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
                                                                                       Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                                                          at io.github.jp1017.android_serial_port.SerialPortFinder$Driver.getDevices(SerialPortFinder.java:48)
                                                                                          at io.github.jp1017.android_serial_port.SerialPortFinder.getAllDevices(SerialPortFinder.java:90)
                                                                                          at io.github.jp1017.android_serial_port.sample.SerialPortPreferences.onCreate(SerialPortPreferences.java:44)
                                                                                          at android.app.Activity.performCreate(Activity.java:6666)
                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789) 
                                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                                          at android.os.Looper.loop(Looper.java:203) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6251) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by xulingchung2016** [comment]
好像是找不到串口设备

**Comment by jp1017** [comment]
你是啥手机,带串口?我们是自己硬件, 有自己添加的串口
可以命令查看下, 到这里/dev/ttyS*看看有没有,然后看下权限,

**Comment by jp1017** [comment]
1. 设备肯定很多的,就看最后ttyS**这样的是串口
2. 系统签名需要自己编译系统,里面有509和408的文件,搞出来,就好办?
3. 你们也是自己硬件系统?

**Comment by xulingchung2016** [comment]
是的，我们串口工程师说，串口路径是dev/ttyMT1.但是执行的时候说是没有权限读写。但是那个文件已经是crwxrwxrwx了。

**Comment by jp1017** [comment]
那就另一个原因了, root权限或系统签名
